GET http://localhost:8081/employee

###

GET http://localhost:8081/employee/1

###

POST http://localhost:8081/employee
Content-Type: application/json

{
  "id":0,
  "name":"Pet",
  "position":"Writer",
  "clock_rate":160
}

###

DELETE http://localhost:8081/employee/6

###

GET http://localhost:8081/employee/search?name=Maksim+Maksimov

###

GET http://localhost:8081/timetrack

###

GET http://localhost:8081/timetrack/6

###

POST http://localhost:8081/timetrack/arrival
Content-Type: application/json

{
  "id": 0,
  "id_employee": 5
}

###

POST http://localhost:8081/timetrack/leave
Content-Type: application/json

{
  "id": 6
}

###

DELETE http://localhost:8081/timetrack/7

###

GET http://localhost:8081/timetrack/search?id_employee=5&date=2020-12-05
